# Generated by Django 2.1.2 on 2018-10-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokegutkowo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='owner_about',
            field=models.TextField(verbose_name='O właścicielu'),
        ),
    ]
