# Generated by Django 2.1.2 on 2018-10-20 07:40

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokegutkowo', '0002_auto_20181007_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Tytuł postu')),
                ('context', ckeditor.fields.RichTextField(verbose_name='Treść postu')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokegutkowo.Players')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posty',
            },
        ),
        migrations.AlterField(
            model_name='settings',
            name='owner_acc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokegutkowo.Players'),
        ),
    ]
